# Insert 20 Aflac Claims into DynamoDB
# Run this after creating the ClaimsAuditTrail table

$claims = @(
    '{"ClaimId":{"S":"AFLAC-20260201-001"},"Timestamp":{"S":"2026-01-12T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-HOSP-2024-001"},"ClaimAmount":{"N":"1500"},"ClaimDescription":{"S":"Hospital confinement 3 days pneumonia"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Hospital Indemnity 500/day for 3 days approved"},"ConfidenceScore":{"N":"0.96"},"ClauseReferences":{"L":[{"S":"AFLAC-HOSP-2.1"},{"S":"AFLAC-HOSP-3.2"}]},"RequiredDocuments":{"L":[{"S":"Hospital Records"},{"S":"Medical Reports"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-002"},"Timestamp":{"S":"2026-01-13T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CANCER-2024-015"},"ClaimAmount":{"N":"25000"},"ClaimDescription":{"S":"Breast cancer Stage 2 diagnosis"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Cancer policy 25000 lump sum approved"},"ConfidenceScore":{"N":"0.98"},"ClauseReferences":{"L":[{"S":"AFLAC-CANCER-4.1"},{"S":"AFLAC-CANCER-4.3"}]},"RequiredDocuments":{"L":[{"S":"Pathology Report"},{"S":"Medical Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-003"},"Timestamp":{"S":"2026-01-14T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-ACCIDENT-2024-007"},"ClaimAmount":{"N":"750"},"ClaimDescription":{"S":"ER treatment fractured wrist workplace fall"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Accident policy ER 350 plus fracture 400 approved"},"ConfidenceScore":{"N":"0.94"},"ClauseReferences":{"L":[{"S":"AFLAC-ACCIDENT-5.2"},{"S":"AFLAC-ACCIDENT-6.1"}]},"RequiredDocuments":{"L":[{"S":"ER Records"},{"S":"X-Ray Reports"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-004"},"Timestamp":{"S":"2026-01-15T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-DISABILITY-2024-022"},"ClaimAmount":{"N":"6000"},"ClaimDescription":{"S":"Disability 12 weeks knee surgery recovery"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Disability 500/week for 12 weeks approved"},"ConfidenceScore":{"N":"0.92"},"ClauseReferences":{"L":[{"S":"AFLAC-DISABILITY-7.1"},{"S":"AFLAC-DISABILITY-7.3"}]},"RequiredDocuments":{"L":[{"S":"Surgery Records"},{"S":"Doctor Statement"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-005"},"Timestamp":{"S":"2026-01-16T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CRITICAL-2024-033"},"ClaimAmount":{"N":"15000"},"ClaimDescription":{"S":"Heart attack emergency angioplasty ICU"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Critical Illness 15000 heart attack approved"},"ConfidenceScore":{"N":"0.97"},"ClauseReferences":{"L":[{"S":"AFLAC-CRITICAL-8.2"},{"S":"AFLAC-CRITICAL-8.5"}]},"RequiredDocuments":{"L":[{"S":"Hospital Records"},{"S":"Cardiac Reports"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-006"},"Timestamp":{"S":"2026-01-17T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-HOSP-2024-041"},"ClaimAmount":{"N":"2000"},"ClaimDescription":{"S":"ICU 2 days allergic reaction anaphylaxis"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Hospital ICU 1000/day for 2 days approved"},"ConfidenceScore":{"N":"0.95"},"ClauseReferences":{"L":[{"S":"AFLAC-HOSP-2.4"},{"S":"AFLAC-HOSP-2.1"}]},"RequiredDocuments":{"L":[{"S":"ICU Records"},{"S":"Medical Reports"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-007"},"Timestamp":{"S":"2026-01-18T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-ACCIDENT-2024-012"},"ClaimAmount":{"N":"2500"},"ClaimDescription":{"S":"Dismemberment loss finger machinery accident"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Accident dismemberment 2500 approved"},"ConfidenceScore":{"N":"0.93"},"ClauseReferences":{"L":[{"S":"AFLAC-ACCIDENT-6.4"},{"S":"AFLAC-ACCIDENT-5.1"}]},"RequiredDocuments":{"L":[{"S":"Accident Report"},{"S":"Medical Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-008"},"Timestamp":{"S":"2026-01-19T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CANCER-2024-008"},"ClaimAmount":{"N":"5000"},"ClaimDescription":{"S":"Chemotherapy 10 sessions colon cancer"},"DecisionStatus":{"S":"Covered"},"Explanation":{"S":"Cancer 500 per session for 10 approved"},"ConfidenceScore":{"N":"0.96"},"ClauseReferences":{"L":[{"S":"AFLAC-CANCER-4.6"},{"S":"AFLAC-CANCER-4.1"}]},"RequiredDocuments":{"L":[{"S":"Treatment Records"},{"S":"Oncology Reports"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-009"},"Timestamp":{"S":"2026-01-20T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CANCER-2024-003"},"ClaimAmount":{"N":"25000"},"ClaimDescription":{"S":"Basal cell carcinoma skin cancer"},"DecisionStatus":{"S":"Not Covered"},"Explanation":{"S":"Excluded basal cell skin cancer denied"},"ConfidenceScore":{"N":"0.91"},"ClauseReferences":{"L":[{"S":"AFLAC-CANCER-9.1"},{"S":"AFLAC-CANCER-9.3"}]},"RequiredDocuments":{"L":[{"S":"Pathology Report"},{"S":"Medical Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-010"},"Timestamp":{"S":"2026-01-21T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-HOSP-2024-019"},"ClaimAmount":{"N":"1000"},"ClaimDescription":{"S":"Cosmetic rhinoplasty hospital admission"},"DecisionStatus":{"S":"Not Covered"},"Explanation":{"S":"Cosmetic procedure excluded denied"},"ConfidenceScore":{"N":"0.97"},"ClauseReferences":{"L":[{"S":"AFLAC-HOSP-9.2"},{"S":"AFLAC-HOSP-9.4"}]},"RequiredDocuments":{"L":[{"S":"Hospital Records"},{"S":"Surgical Notes"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-011"},"Timestamp":{"S":"2026-01-22T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-ACCIDENT-2024-018"},"ClaimAmount":{"N":"800"},"ClaimDescription":{"S":"Back injury preexisting disc disease"},"DecisionStatus":{"S":"Not Covered"},"Explanation":{"S":"Preexisting condition excluded denied"},"ConfidenceScore":{"N":"0.88"},"ClauseReferences":{"L":[{"S":"AFLAC-ACCIDENT-9.5"},{"S":"AFLAC-ACCIDENT-9.1"}]},"RequiredDocuments":{"L":[{"S":"Medical History"},{"S":"MRI Reports"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-012"},"Timestamp":{"S":"2026-01-23T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-DISABILITY-2024-027"},"ClaimAmount":{"N":"4000"},"ClaimDescription":{"S":"Mental health depression outpatient 8 weeks"},"DecisionStatus":{"S":"Not Covered"},"Explanation":{"S":"Mental health without hospitalization excluded"},"ConfidenceScore":{"N":"0.94"},"ClauseReferences":{"L":[{"S":"AFLAC-DISABILITY-9.6"},{"S":"AFLAC-DISABILITY-9.1"}]},"RequiredDocuments":{"L":[{"S":"Treatment Records"},{"S":"Psychiatrist Notes"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-013"},"Timestamp":{"S":"2026-01-24T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CRITICAL-2024-031"},"ClaimAmount":{"N":"15000"},"ClaimDescription":{"S":"TIA resolved 4 hours not stroke"},"DecisionStatus":{"S":"Not Covered"},"Explanation":{"S":"TIA does not meet stroke definition denied"},"ConfidenceScore":{"N":"0.92"},"ClauseReferences":{"L":[{"S":"AFLAC-CRITICAL-8.3"},{"S":"AFLAC-CRITICAL-9.2"}]},"RequiredDocuments":{"L":[{"S":"ER Records"},{"S":"Neurologist Report"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-014"},"Timestamp":{"S":"2026-01-25T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-HOSP-2024-025"},"ClaimAmount":{"N":"3500"},"ClaimDescription":{"S":"Hospital 7 days observation vs admission unclear"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"Observation status needs clarification"},"ConfidenceScore":{"N":"0.71"},"ClauseReferences":{"L":[{"S":"AFLAC-HOSP-2.1"},{"S":"AFLAC-HOSP-2.6"}]},"RequiredDocuments":{"L":[{"S":"Hospital Records"},{"S":"Admission Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-015"},"Timestamp":{"S":"2026-01-26T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CANCER-2024-038"},"ClaimAmount":{"N":"25000"},"ClaimDescription":{"S":"Melanoma in situ possible microinvasion"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"In situ vs invasive needs medical review"},"ConfidenceScore":{"N":"0.68"},"ClauseReferences":{"L":[{"S":"AFLAC-CANCER-4.1"},{"S":"AFLAC-CANCER-9.3"}]},"RequiredDocuments":{"L":[{"S":"Pathology Report"},{"S":"Biopsy Results"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-016"},"Timestamp":{"S":"2026-01-27T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-ACCIDENT-2024-041"},"ClaimAmount":{"N":"1200"},"ClaimDescription":{"S":"ACL tear recreational vs organized sports unclear"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"Sports exclusion needs investigation"},"ConfidenceScore":{"N":"0.64"},"ClauseReferences":{"L":[{"S":"AFLAC-ACCIDENT-5.1"},{"S":"AFLAC-ACCIDENT-9.8"}]},"RequiredDocuments":{"L":[{"S":"MRI Report"},{"S":"Incident Statement"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-017"},"Timestamp":{"S":"2026-01-28T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-DISABILITY-2024-029"},"ClaimAmount":{"N":"10000"},"ClaimDescription":{"S":"Fibromyalgia 20 weeks subjective symptoms"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"Chronic subjective condition needs IME"},"ConfidenceScore":{"N":"0.59"},"ClauseReferences":{"L":[{"S":"AFLAC-DISABILITY-7.2"},{"S":"AFLAC-DISABILITY-9.6"}]},"RequiredDocuments":{"L":[{"S":"Doctor Statement"},{"S":"Medical Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-018"},"Timestamp":{"S":"2026-01-29T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-CRITICAL-2024-051"},"ClaimAmount":{"N":"15000"},"ClaimDescription":{"S":"Kidney failure dialysis preexisting question"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"Preexisting condition investigation needed"},"ConfidenceScore":{"N":"0.66"},"ClauseReferences":{"L":[{"S":"AFLAC-CRITICAL-8.6"},{"S":"AFLAC-CRITICAL-9.1"}]},"RequiredDocuments":{"L":[{"S":"Medical History"},{"S":"Dialysis Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-019"},"Timestamp":{"S":"2026-01-30T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-HOSP-2024-036"},"ClaimAmount":{"N":"2500"},"ClaimDescription":{"S":"Pneumonia 5 days prior outpatient treatment"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"Medical necessity of admission questioned"},"ConfidenceScore":{"N":"0.73"},"ClauseReferences":{"L":[{"S":"AFLAC-HOSP-2.1"},{"S":"AFLAC-HOSP-2.8"}]},"RequiredDocuments":{"L":[{"S":"Hospital Records"},{"S":"Outpatient Records"}]}}',
    '{"ClaimId":{"S":"AFLAC-20260201-020"},"Timestamp":{"S":"2026-01-31T10:00:00Z"},"PolicyNumber":{"S":"AFLAC-ACCIDENT-2024-034"},"ClaimAmount":{"N":"1500"},"ClaimDescription":{"S":"Concussion ER plus followup not disabling"},"DecisionStatus":{"S":"Manual Review"},"Explanation":{"S":"Follow-up benefit eligibility unclear"},"ConfidenceScore":{"N":"0.70"},"ClauseReferences":{"L":[{"S":"AFLAC-ACCIDENT-5.2"},{"S":"AFLAC-ACCIDENT-6.2"}]},"RequiredDocuments":{"L":[{"S":"ER Records"},{"S":"Follow-up Notes"}]}}'
)

$inserted = 0
Write-Host "Inserting 20 claims into ClaimsAuditTrail..." -ForegroundColor Green

foreach ($claim in $claims) {
    $claim | Out-File -FilePath "temp-claim.json" -Encoding ASCII -NoNewline
    
    aws dynamodb put-item --table-name ClaimsAuditTrail --item file://temp-claim.json 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        $inserted++
        $claimId = ($claim | ConvertFrom-Json).ClaimId.S
        Write-Host "$claimId ✓" -ForegroundColor Green
    } else {
        Write-Host "Failed to insert claim" -ForegroundColor Red
    }
}

if (Test-Path "temp-claim.json") { Remove-Item "temp-claim.json" }

Write-Host "`nInserted $inserted / 20 claims successfully!" -ForegroundColor Cyan
Write-Host "Now restart your backend: cd src\ClaimsRagBot.Api; dotnet run" -ForegroundColor Yellow
